### PR TITLE
Added create playlist option!

### PR DESCRIPTION
**Pull request by tashima42**
As requested on #6, I added a create playlist button, this is done via the Spotify API, using the create playlist and add playlist endpoints.
I tried to make minimum changes to the code, if you have any comments or don't want to merge, please let me know!

Working deployment if you want to test it: https://receiptify.tashima.click (because Spotify is in dev mode, please send your email to audios_sounds.0i@icloud.com so I can add it in my testers list)

Update: Since it's been some time, I've disabled the preview website, if someone really wants to use it, I could enable it again, so let me know here.

### CODE REVIEW

**Comment by zaneshaw** [comment]
Your preview website isn't currently working. Auth button...
image

**Comment by tashima42** [comment]
> Your preview website isn't currently working. Auth button...
> image

Hey, @squidee100 My Spotify Client is in dev mode, so I have to manually add users in a whitelist. Can you please send your Spotify email to audios_sounds.0i@icloud.com?

**Comment by tashima42** [comment]
Done, @squidee100

**Comment by tashima42** [comment]
This repo isn't used anymore and receiptify has implemented this feature.

**Pull request closed without merging**
